apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fullstack-app.fullname" . }}-config
data:
  DJANGO_DEBUG: {{ .Values.django.debug | quote }}
  DJANGO_ALLOWED_HOSTS: {{ .Values.django.allowedHosts | join "," | quote }}
  DATABASE_URL: "postgres://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@{{ include "fullstack-app.fullname" . }}-postgres:5432/{{ .Values.postgres.database }}"
  REDIS_URL: "redis://{{ include "fullstack-app.fullname" . }}-redis:6379/0"
  CELERY_BROKER_URL: "redis://{{ include "fullstack-app.fullname" . }}-redis:6379/0"
  CELERY_RESULT_BACKEND: "redis://{{ include "fullstack-app.fullname" . }}-redis:6379/1"
  DB_HOST: fullstack-app-rel-postgres
  DB_PORT: "5432"