apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullstack-app.fullname" . }}-django
  labels:
    {{- include "fullstack-app.labels" . | nindent 4 }}
    app: django
spec:
  replicas: {{ .Values.django.replicaCount }}
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        {{- include "fullstack-app.labels" . | nindent 8 }}
        app: django
    spec:
      containers:
      - name: django
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8000
          name: http
        envFrom:
        - configMapRef:
            name: {{ include "fullstack-app.fullname" . }}-config
        readinessProbe:
          httpGet:
            path: /api/v1/hello
            port: 8000
          failureThreshold: 3
          periodSeconds: 10